version: "3"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8001:80"
    volumes:
      - ./htdocs:/var/www/html
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    build: ./docker
    volumes:
      - ./htdocs:/var/www/html
  mysql:
    image: mariadb:10.4
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: null
      MYSQL_PASSWORD: null
      MYSQL_ROOT_PASSWORD: example
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./mysql/data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:mysql
    ports:
      - 8000:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

#   elasticsearch:
#     image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
#     volumes:
#       - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
#       - ./elasticsearch:/usr/share/elasticsearch/data
#     ports:
#       - "9200:9200"
#       - "9300:9300"
#     environment:
#       ES_JAVA_OPTS: "-Xmx256m -Xms256m"
#       ELASTIC_PASSWORD: changeme
#       discovery.type: single-node
#     networks:
#       - elk

#   logstash:
#     volumes:
#       - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
#       - ./logstash/pipeline:/usr/share/logstash/pipeline
#     ports:
#       - "5044:5044"
#       - "5000:5000/tcp"
#       - "5000:5000/udp"
#       - "9600:9600"
#     environment:
#       LS_JAVA_OPTS: "-Xmx256m -Xms256m"
#     networks:
#       - elk
#     depends_on:
#       - elasticsearch

#   kibana:
#     volumes:
#       - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
#     ports:
#       - "5601:5601"
#     networks:
#       - elk
#     depends_on:
#       - elasticsearch

# networks:
#   elk:
#     driver: bridge

volumes:
  persistent: null
